# Where should we write the GIF?
Output demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 12
Set Width 1366
Set Height 768

# Type a command in the terminal.
Type "cargo run"

# Pause for dramatic effect...
Sleep 2s

# Run the command by pressing enter.
Enter

Sleep 2s

#adjust the frequency down
Down 100
Up 100

Sleep 1s

Right 1
Up 100
Down 50

Sleep 1s

Right 1
Up@2s 4

Right 1
Down@2s 45

# Admire the output for a bit.
Sleep 2s
